# playground for java 11
version: "3.8"

services:
  playground:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: playground
    ports:
      - "8081:8081"
    volumes:
      - type: bind
        source: .
        target: /app
    working_dir: /app
    networks:
      - spring_test

  spring_intro:
    build:
      dockerfile: ./spring-intro/Dockerfile
    container_name: spring_intro
    ports:
      - "10011:8080"
    volumes:
      - type: bind
        source: ./spring-intro
        target: /app
    working_dir: /app
    networks:
      - spring_test

  mysql:
    container_name: spring_mysql
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: spring_test
      MYSQL_USER: spring_test
      MYSQL_PASSWORD: 1234
    networks:
      - spring_test

networks:
  spring_test:
    driver: bridge
