# playground for java 11
version: "3.8"

services:
  playground:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: playground
    volumes:
      - type: bind
        source: .
        target: /app
    working_dir: /app
